# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_load.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveLoad(object):
    def setupUi(self, SaveLoad):
        SaveLoad.setObjectName("SaveLoad")
        SaveLoad.resize(402, 160)
        SaveLoad.setStyleSheet("")
        self.widget = QtWidgets.QWidget(SaveLoad)
        self.widget.setGeometry(QtCore.QRect(0, 0, 401, 311))
        self.widget.setStyleSheet("color:black;\n"
"\n"
"QDoubleSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QDoubleSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListWidget\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QListWidget:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListView{\n"
"background-color:  rgb(255, 255, 255);\n"
"  color: white;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:  rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QComboBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"\n"
"QTextBrowser\n"
"{\n"
"background-color: black;\n"
"color:white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 8px;\n"
"color:black;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"\n"
"color:balck;\n"
"}\n"
"QSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.SubjectName = QtWidgets.QTextEdit(self.widget)
        self.SubjectName.setGeometry(QtCore.QRect(270, 70, 121, 21))
        self.SubjectName.setStyleSheet("QTextEdit\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"\n"
"color:balck;\n"
"}\n"
"QTextEdit:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}")
        self.SubjectName.setObjectName("SubjectName")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(260, 30, 3, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 41))
        self.label.setObjectName("label")
        self.ValveM6_3 = QtWidgets.QLabel(self.widget)
        self.ValveM6_3.setGeometry(QtCore.QRect(280, 30, 101, 20))
        self.ValveM6_3.setObjectName("ValveM6_3")
        self.Load_windowButt = QtWidgets.QPushButton(self.widget)
        self.Load_windowButt.setGeometry(QtCore.QRect(230, 130, 113, 32))
        self.Load_windowButt.setObjectName("Load_windowButt")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 241, 41))
        self.label_2.setObjectName("label_2")
        self.Save_windowButt = QtWidgets.QPushButton(self.widget)
        self.Save_windowButt.setGeometry(QtCore.QRect(90, 130, 113, 32))
        self.Save_windowButt.setObjectName("Save_windowButt")

        self.retranslateUi(SaveLoad)
        QtCore.QMetaObject.connectSlotsByName(SaveLoad)

    def retranslateUi(self, SaveLoad):
        _translate = QtCore.QCoreApplication.translate
        SaveLoad.setWindowTitle(_translate("SaveLoad", "Form"))
        self.SubjectName.setHtml(_translate("SaveLoad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Subject1</p></body></html>"))
        self.label.setText(_translate("SaveLoad", "For saving current setup, click on Save"))
        self.ValveM6_3.setText(_translate("SaveLoad", "Subject\'s Name"))
        self.Load_windowButt.setText(_translate("SaveLoad", "Load"))
        self.label_2.setText(_translate("SaveLoad", "For loading sxiting setup, click on Load"))
        self.Save_windowButt.setText(_translate("SaveLoad", "Save"))
